### ISSUE TITLE
Validate ownership of the dist bucket before uploading deployment packages

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-samples/aws-media-insights-content-localization#105]
Update script statements like this:
aws s3 sync $global_dist_dir s3://$global_bucket/aws-media-insights-engine/$version/
aws s3 sync $regional_dist_dir s3://${regional_bucket}-${region}/aws-media-insights-engine/$version/

To include checks like this before running s3 sync or cp:
aws s3api head-bucket --bucket $global_bucket --expected-bucket-owner $bucket_account
aws s3api head-bucket --bucket $regional_bucket --expected-bucket-owner $bucket_account

The head-bucket command will return a non-zero result (API returns a 403) if the bucket ownership doesn’t match. If you have error handling set to short-circuit the script, the above statements would stop the script before uploading.

Directly uploading to regional buckets means checking each bucket before uploading.

**Comment by aburkleaux-amazon** [comment]
This is included in the PR to merge from CAS (#139 )

**Comment by ianwow** [comment]
Fixed here:
https://github.com/aws-samples/aws-media-insights-content-localization/blob/dc945e895c0f4d4a6159e383368c9ce9ce909dc8/deployment/build-s3-dist.sh#L351

This issue will automatically close when #139 is merged.
